[package]
name = "qzhcore/input"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A configurable Rojo-ready wrapper for Roblox's Input Action System."
license = "MIT"
authors = ["qzhcore"]
include = [
	"lib",
	"Linking.lua",
	"default.project.json",
	"pack.project.json",
	"testing.project.json",
	"README.md",
	"LICENSE",
]
exclude = [
	".github",
	"sourcemap.json",
]

[dependencies]
